# Generated by Django 5.1.2 on 2024-10-30 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('min_confidence', models.FloatField(default=0.2)),
            ],
        ),
        migrations.CreateModel(
            name='Subquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('min_confidence', models.FloatField(default=0.2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subquestions', to='api.question')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='api.question')),
                ('subquestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='api.subquestion')),
            ],
        ),
    ]
